Feature/my review: my-review 컴포넌트 구현, bagic header 스타일 변경
star-to/star-to-client pull request #29
Opened 2022-02-03 07:20 UTC by hyesunie

2022-02-05 09:17 UTC, fjqm941025 requested changes

2022-02-05 09:17 UTC, fjqm941025 commented on src/ts/component/main/my-review.ts
> +  init = (): void => {
이거 이렇게 다 바꾼 이유가 있나여?? 보통 `init():void {}` 의 형태를 더 추천하고 있어서여!

2022-02-05 09:17 UTC, fjqm941025 commented on src/ts/component/main/my-review.ts
> +    for (let j = 1; j <= 5; j++) {
숫자 5에 대한 의미가 부족해서 다른사람이 헷갈릴수도 있어요! `const MAX_COUTING_STARS = 5` 등의 방식으로 매직넘버를 만들어도 좋을 거 같아요!

2022-02-14 05:41 UTC, hyesunie commented on src/ts/component/main/my-review.ts
> +  init = (): void => {
함수 내부의 this를 고정해야할 일이 생겨서 한개를 저렇게 바꿨는데, 함수 형태를 통일하면 좋을 것 같아서 저런식으로 변경했어요!

2022-02-15 06:12 UTC, merged